---
- name: copy fail2ban config file
  copy: >
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - { src: iptables-ipset-allports.conf, dest: /etc/fail2ban/action.d/iptables-ipset-allports.conf }
  notify:
    - restart fail2ban

- name: copy fail2ban configs 
  template: src={{ item }}.j2 dest=/{{ item }}
  with_items:
    - etc/fail2ban/jail.local
    - etc/fail2ban/fail2ban.local
  notify:
    - restart fail2ban

